NICHES = [
    {"id": "restaurantes", "label": "Restaurantes"},
    {"id": "bares", "label": "Bares e Lanchonetes"},
    {"id": "hamburguerias", "label": "Hamburguerias"},
    {"id": "pizzarias", "label": "Pizzarias"},
    {"id": "cafeterias", "label": "Cafeterias"},
    {"id": "acai", "label": "Açaí e Sorveterias"},
    {"id": "beleza", "label": "Salões de Beleza"},
    {"id": "barbearias", "label": "Barbearias"},
    {"id": "estetica", "label": "Clínicas de Estética"},
    {"id": "academias", "label": "Academias"},
    {"id": "padarias", "label": "Padarias e Confeitarias"},
    {"id": "petshop", "label": "Petshops e Veterinárias"},
    {"id": "advocacia", "label": "Escritórios de Advocacia"},
    {"id": "imobiliarias", "label": "Imobiliárias"},
    {"id": "odontologia", "label": "Clínicas Odontológicas"},
    {"id": "moda", "label": "Lojas de Roupas"},
    {"id": "mecanica", "label": "Mecânicas de Automóveis"},
    {"id": "moveis", "label": "Lojas de Móveis"},
    {"id": "cursos", "label": "Escolas e Cursos"},
    {"id": "farmacias", "label": "Farmácias"},
    {"id": "reformas", "label": "Reformas e Construção"},
    {"id": "limpeza", "label": "Serviços de Limpeza"},
    {"id": "floricultura", "label": "Floriculturas"},
    {"id": "fotografia", "label": "Fotógrafos"},
]

ESTADOS = [
    {"uf": "AC", "nome": "Acre"},
    {"uf": "AL", "nome": "Alagoas"},
    {"uf": "AP", "nome": "Amapá"},
    {"uf": "AM", "nome": "Amazonas"},
    {"uf": "BA", "nome": "Bahia"},
    {"uf": "CE", "nome": "Ceará"},
    {"uf": "DF", "nome": "Distrito Federal"},
    {"uf": "ES", "nome": "Espírito Santo"},
    {"uf": "GO", "nome": "Goiás"},
    {"uf": "MA", "nome": "Maranhão"},
    {"uf": "MT", "nome": "Mato Grosso"},
    {"uf": "MS", "nome": "Mato Grosso do Sul"},
    {"uf": "MG", "nome": "Minas Gerais"},
    {"uf": "PA", "nome": "Pará"},
    {"uf": "PB", "nome": "Paraíba"},
    {"uf": "PR", "nome": "Paraná"},
    {"uf": "PE", "nome": "Pernambuco"},
    {"uf": "PI", "nome": "Piauí"},
    {"uf": "RJ", "nome": "Rio de Janeiro"},
    {"uf": "RN", "nome": "Rio Grande do Norte"},
    {"uf": "RS", "nome": "Rio Grande do Sul"},
    {"uf": "RO", "nome": "Rondônia"},
    {"uf": "RR", "nome": "Roraima"},
    {"uf": "SC", "nome": "Santa Catarina"},
    {"uf": "SP", "nome": "São Paulo"},
    {"uf": "SE", "nome": "Sergipe"},
    {"uf": "TO", "nome": "Tocantins"},
]


def get_public():
    return {
        "nichos": [{"id": n["id"], "label": n["label"]} for n in NICHES],
        "estados": ESTADOS,
    }