# proposito: a lista de nichos que a busca oferece
NICHES = [
    {"id": "restaurantes", "label": "Restaurantes",
     "variacoes": ["restaurantes", "cantina", "comida caseira", "marmita", "grelhados", "self service"]},
    {"id": "bares", "label": "Bares e Lanchonetes",
     "variacoes": ["bares", "lanchonetes", "boteco", "pastelaria", "espetinhos"]},
    {"id": "hamburguerias", "label": "Hamburguerias",
     "variacoes": ["hamburguerias", "hamburguer artesanal", "smash burger"]},
    {"id": "pizzarias", "label": "Pizzarias",
     "variacoes": ["pizzarias", "pizza delivery", "forneria"]},
    {"id": "cafeterias", "label": "Cafeterias",
     "variacoes": ["cafeterias", "café especial", "brunch", "casa de chá"]},
    {"id": "acai", "label": "Açaí e Sorveterias",
     "variacoes": ["açaí", "sorveterias", "gelateria", "milk shake"]},
    {"id": "beleza", "label": "Salões de Beleza",
     "variacoes": ["salão de beleza", "cabeleireiro", "manicure", "design de sobrancelhas", "mega hair"]},
    {"id": "barbearias", "label": "Barbearias",
     "variacoes": ["barbearias", "barbeiro", "corte masculino"]},
    {"id": "estetica", "label": "Clínicas de Estética",
     "variacoes": ["clínica de estética", "estética corporal", "harmonização facial", "depilação a laser", "massoterapia"]},
    {"id": "academias", "label": "Academias",
     "variacoes": ["academias", "musculação", "crossfit", "pilates", "boxe", "natação", "yoga"]},
    {"id": "padarias", "label": "Padarias e Confeitarias",
     "variacoes": ["padarias", "confeitarias", "panificadora", "doceria", "bolo de festa"]},
    {"id": "petshop", "label": "Petshops e Veterinárias",
     "variacoes": ["petshops", "veterinária", "banho e tosa", "pet shop 24h", "adestramento"]},
    {"id": "advocacia", "label": "Escritórios de Advocacia",
     "variacoes": ["advocacia", "advogados", "advogado trabalhista", "advogado previdenciário", "consultoria jurídica"]},
    {"id": "imobiliarias", "label": "Imobiliárias",
     "variacoes": ["imobiliárias", "corretores de imóveis", "administração de imóveis"]},
    {"id": "odontologia", "label": "Clínicas Odontológicas",
     "variacoes": ["dentista", "clínica odontológica", "aparelho ortodôntico", "implante dentário", "clareamento dental"]},
    {"id": "moda", "label": "Lojas de Roupas",
     "variacoes": ["lojas de roupas", "boutique", "moda feminina", "moda masculina", "brecho", "loja infantil"]},
    {"id": "mecanica", "label": "Mecânicas de Automóveis",
     "variacoes": ["oficina mecânica", "mecânica de automóveis", "auto center", "troca de óleo", "alinhamento"]},
    {"id": "moveis", "label": "Lojas de Móveis",
     "variacoes": ["lojas de móveis", "móveis planejados", "marcenaria", "estofados"]},
    {"id": "cursos", "label": "Escolas e Cursos",
     "variacoes": ["cursos", "escolas de idiomas", "curso de informática", "autoescola", "curso preparatório"]},
    {"id": "farmacias", "label": "Farmácias",
     "variacoes": ["farmácias", "drogaria", "farmácia de manipulação"]},
    {"id": "reformas", "label": "Reformas e Construção",
     "variacoes": ["reformas", "construção civil", "pedreiro", "eletricista", "encanador", "pintor"]},
    {"id": "limpeza", "label": "Serviços de Limpeza",
     "variacoes": ["serviços de limpeza", "dedetização", "limpeza pós-obra", "diarista"]},
    {"id": "floricultura", "label": "Floriculturas",
     "variacoes": ["floriculturas", "flores", "cesta de café da manhã"]},
    {"id": "fotografia", "label": "Fotógrafos",
     "variacoes": ["fotógrafos", "fotografia", "ensaio fotográfico", "fotografia de casamento"]},
    {"id": "chaveiro", "label": "Chaveiros",
     "variacoes": ["chaveiro", "chaveiro 24h"]},
    {"id": "vidracaria", "label": "Vidraçarias",
     "variacoes": ["vidraçarias", "vidros temperados", "box para banheiro"]},
    {"id": "grafica", "label": "Gráficas",
     "variacoes": ["gráficas", "gráfica rápida", "impressão digital", "plotter"]},
    {"id": "contabilidade", "label": "Contabilidade",
     "variacoes": ["contabilidade", "contador", "escritório contábil", "abrir empresa"]},
    {"id": "seguros", "label": "Corretoras de Seguros",
     "variacoes": ["corretora de seguros", "seguro de carro", "seguro de vida", "plano de saúde"]},
    {"id": "lavajato", "label": "Lava-Jatos",
     "variacoes": ["lava-jato", "lava car", "estética automotiva", "higienização de carro"]},
    {"id": "otica", "label": "Óticas",
     "variacoes": ["óticas", "oculos de grau", "exame de vista"]},
    {"id": "celular", "label": "Assistência de Celular",
     "variacoes": ["assistência técnica celular", "conserto de celular", "troca de tela"]},
    {"id": "suplementos", "label": "Lojas de Suplementos",
     "variacoes": ["lojas de suplementos", "suplementação", "whey protein"]},
    {"id": "buffet", "label": "Buffets e Festas",
     "variacoes": ["buffet infantil", "salão de festas", "decoração de festas"]},
    {"id": "pousadas", "label": "Pousadas e Hotéis",
     "variacoes": ["pousadas", "hotéis", "hostel", "aluguel por temporada"]},
    {"id": "distribuidora", "label": "Distribuidoras de Bebidas",
     "variacoes": ["distribuidora de bebidas", "adega", "delivery de bebidas"]},
]

ESTADOS = [
    {"uf": "AC", "nome": "Acre"},
    {"uf": "AL", "nome": "Alagoas"},
    {"uf": "AP", "nome": "Amapá"},
    {"uf": "AM", "nome": "Amazonas"},
    {"uf": "BA", "nome": "Bahia"},
    {"uf": "CE", "nome": "Ceará"},
    {"uf": "DF", "nome": "Distrito Federal"},
    {"uf": "ES", "nome": "Espírito Santo"},
    {"uf": "GO", "nome": "Goiás"},
    {"uf": "MA", "nome": "Maranhão"},
    {"uf": "MT", "nome": "Mato Grosso"},
    {"uf": "MS", "nome": "Mato Grosso do Sul"},
    {"uf": "MG", "nome": "Minas Gerais"},
    {"uf": "PA", "nome": "Pará"},
    {"uf": "PB", "nome": "Paraíba"},
    {"uf": "PR", "nome": "Paraná"},
    {"uf": "PE", "nome": "Pernambuco"},
    {"uf": "PI", "nome": "Piauí"},
    {"uf": "RJ", "nome": "Rio de Janeiro"},
    {"uf": "RN", "nome": "Rio Grande do Norte"},
    {"uf": "RS", "nome": "Rio Grande do Sul"},
    {"uf": "RO", "nome": "Rondônia"},
    {"uf": "RR", "nome": "Roraima"},
    {"uf": "SC", "nome": "Santa Catarina"},
    {"uf": "SP", "nome": "São Paulo"},
    {"uf": "SE", "nome": "Sergipe"},
    {"uf": "TO", "nome": "Tocantins"},
]


def get_public():
    return {
        "nichos": [{"id": n["id"], "label": n["label"]} for n in NICHES],
        "estados": ESTADOS,
    }


def variacoes_para(query):
    """Retorna a lista de termos de busca para um nicho (ou o próprio termo)."""
    q = (query or "").strip().lower()
    for n in NICHES:
        if n["id"] == q or n["label"].lower() == q:
            return list(n.get("variacoes") or [query])
    return [query]
